name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 24
          - 22
        os:
          - ubuntu-latest
          - ubuntu-22.04-arm
          - macos-latest
          - windows-latest
        script:
          - tsc
          - check-format
          - test
        exclude:
          - os: windows-latest
            script: check-format
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm ${{ matrix.script }}
